apiVersion: apps/v1
kind: Deployment
metadata:
  name: <your-app-name>
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: <your-app-name>
  template:
    metadata:
      labels:
        app: <your-app-name>
    spec:
      containers:
      - name: <your-app-name>
        image: <your-image-name>  # Replace with your image details (local or registry)
        ports:
        - containerPort: 3000

