apiVersion: v1
kind: Service
metadata:
  name: <your-app-name>-service
spec:
  selector:
    app: <your-app-name>
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 3000  
  type: LoadBalancer  # Makes the service accessible externally
